name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Ngrok của Rinne
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz && tar xf ngrok-v3-stable-linux-amd64.tgz && ./ngrok config add-authtoken 2NNoTTcvlbRCu6VXx8lm14seZ6E_irGzBfSnNLx2t4RSg9pK
    - name: Run sshd
      run: sudo service sshd start   
    - name: Change pass
      run: yes superpass | sudo passwd      
    - name: add user
      run: |
          sudo useradd -m superuser
          yes superpass | sudo passwd superuser
          sudo usermod -aG sudo superuser
    - name: Chạy Container Docker
      run: sudo apt update && sudo apt install lxde -y && startlxde && ./ngrok tcp 22 --region=jp && yes
